// UI reducer types
export const SET_LOADING = 'SET_LOADING';
export const SET_UI_LOADING = 'SET_UI_LOADING';

// User reducer types
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const GET_ALL_LIKES = 'GET_ALL_LIKES';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

// Data reduces types
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_ERROR = 'GET_ALL_POSTS_ERROR';
export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';
export const DELETE_POST = 'DELETE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const GET_ALL_COMMENTS_FOR_POST = 'GET_ALL_COMMENTS_FOR_POST';
export const GET_ALL_COMMENTS_ERROR = 'GET_ALL_COMMENTS_ERROR';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';
export const GET_ALL_USER_POSTS = 'GET_ALL_USER_POSTS';
